export const CategoryList = [
    "Carpenter",
    "Painter",
    "Marble Laying",
    "Granite Laying",
    "Tile Laying",
    "Wood Laying",
    "Electrical",
    "False Ceiling",
    "Glass",
    "Stone",
    "Loose Furniture",
    "Plumber",
    "Civil",
    "Demolition",
    "Fabricator",
    "Paint and Polish",
    "Furniture",
    "Furnishing",
    "Glass Vendor",
    "Modular",
    "AC-Low Side",
    "Deep Cleaning",
    "Equipments",
    "Office Furniture",
    "Lacquered Glass",
    "Carpet",
    "Blinds",
    "Misc",
    "CNC",
    "BarBending",
    "RMC",
    "Upvc",
    "Lift",
    "Generator",
    "Waterproofing",
    "Plants",
    "Branding",
    "Landscape",
    "Glass System",
    "Frosted Film",
    "Mural",
]