export const MaterialsList = [
    "Fan",
    "Paint",
    "Light",
    "Plywood",
    "Laminate",
    "Wood",
    "Hardware",
    "Misc",
    "Seating",
    "Bed",
    "Polish",
    "Wall/ Ceilling",
    "Wire",
    "Conduit",
    "Light fixture",
    "Switches",
    "WC",
    "WB",
    "CP fitting",
    "Sink",
    "Spout",
    "Plaster",
    "Stucture",
    "Screeding",
    "Shuttering",
    "Excavation",
    "RCC",
    "Concrete",
    "MS",
    "Tiles",
    "Terracotta",
    "Granite",
    "Marble",
    "Limestone",
    "Slate",
    "Quartz",
    "Iron",
    "SS",
    "Alumunium",
    "Enamel",
    "Emultion",
    "Glass shutter",
    "Mirror",
    "Kitchen",
    "Wardrobe",
    "Crockery",
    "Panneling",
    "Kitchen Appliances",
    "Door lock",
    "Door bell",
    "Camera",
    "Data",
    "Tv",
    "Floor protection",
    "Office chair",
    "sanitary fittings",
    "Cement",
    "Steel",
    "Aggregate",
    "Redbrick",
    "CementBlock",
    "Flyashblock",
    "Electrical",
    "Plumbing",
    "WPC",
    "uPVC",
    "Scaffolding",
    "Doors",
    "Windows",
    "Waterproofing",
    "Sand",
    "FloorProtection",
    "Grouting",
    "Primer",
    "Putt",
]